src/Entity/Blog.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\BlogRepository")
 * @ORM\HasLifecycleCallbacks
 *  @UniqueEntity(
 * fields={"title"},
 * message="Une autre annonce possede deja ce titre, merci de le modifier"
 * )
 */
class Blog
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractéres !",
     * maxMessage="Le titre ne peut pas faire plus de 255 caractéres")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     *  @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractéres")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire plus de 100 caractéres")
     */
    private $contenu;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ImageBlog", mappedBy="blog", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $imageBlogs;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\TypeBlog", inversedBy="blog")
     * @ORM\JoinColumn(nullable=false)
     */
    private $typeBlog;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="blogs")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="blog", orphanRemoval=true)
     */
    private $comments;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    public function __construct()
    {
        $this->imageBlogs = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

     /**
     * Permet de calculer la note moyenne d'un commentaire
     *
     * @return float
     */
    public function getAvgRatings() {
        $sum = array_reduce($this->comments->toArray(),function($total, $comment) {
            return $total + $comment->getRating();
        }, 0);
        if(count($this->comments) > 0) return $moyenne = $sum / count($this->comments);
        return 0;
    }

    /**
     * Permet de mettre en place la date de création
     *@ORM\PrePersist
     * @return void
     */
    public function prePersist() {
        if(empty($this->createdAt)) {
            $this->createdAt = new \DateTime();
        }
    }
    
    /**
     * Permet d'initialiser le slug
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug() {
        if(empty($this->slug)) {
            $slug = new Slugify();
            $this->slug = $slug->slugify($this->title);        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContenu(): ?string
    {
        return $this->contenu;
    }

    public function setContenu(string $contenu): self
    {
        $this->contenu = $contenu;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    /**
     * @return Collection|ImageBlog[]
     */
    public function getImageBlogs(): Collection
    {
        return $this->imageBlogs;
    }

    public function addImageBlog(ImageBlog $imageBlog): self
    {
        if (!$this->imageBlogs->contains($imageBlog)) {
            $this->imageBlogs[] = $imageBlog;
            $imageBlog->setBlog($this);
        }

        return $this;
    }

    public function removeImageBlog(ImageBlog $imageBlog): self
    {
        if ($this->imageBlogs->contains($imageBlog)) {
            $this->imageBlogs->removeElement($imageBlog);
            // set the owning side to null (unless already changed)
            if ($imageBlog->getBlog() === $this) {
                $imageBlog->setBlog(null);
            }
        }

        return $this;
    }

    public function getTypeBlog(): ?TypeBlog
    {
        return $this->typeBlog;
    }

    public function setTypeBlog(?TypeBlog $typeBlog): self
    {
        $this->typeBlog = $typeBlog;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setBlog($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getBlog() === $this) {
                $comment->setBlog(null);
            }
        }

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity(
 * fields={"email"},
 * message="Une autre utilisateur s'est déja inscrit avec cette adresse email, merci de la modifier ! "
 * )
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Blog", mappedBy="author")
     */
    private $blogs;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Role", mappedBy="users")
     */
    private $userRoles;

    public function __construct()
    {
        $this->blogs = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
    }

    /**
     * return concat
     *
     * @return void
     */
    public function getFullName() {
        return "{$this->firstName} {$this->lastName}";
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    /**
     * @return Collection|Blog[]
     */
    public function getBlogs(): Collection
    {
        return $this->blogs;
    }

    public function addBlog(Blog $blog): self
    {
        if (!$this->blogs->contains($blog)) {
            $this->blogs[] = $blog;
            $blog->setAuthor($this);
        }

        return $this;
    }

    public function removeBlog(Blog $blog): self
    {
        if ($this->blogs->contains($blog)) {
            $this->blogs->removeElement($blog);
            // set the owning side to null (unless already changed)
            if ($blog->getAuthor() === $this) {
                $blog->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles() {
        $roles = [];
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();
        $roles[] = 'ROLE_USER';
        return $roles;
    }

    public function getPassword() {
        return $this->hash;
    }

    public function getSalt() {}

    public function getUsername() {
        return $this->email;
    }

    public function eraseCredentials(){}

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->contains($userRole)) {
            $this->userRoles->removeElement($userRole);
            $userRole->removeUser($this);
        }

        return $this;
    }
}

src/Form/BlogType.php
<?php

namespace App\Form;

use App\Entity\Blog;
use App\Entity\TypeBlog;
use App\Form\ImageBlogType;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class BlogType extends ApplicationType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class,
                  $this->getConfiguration("Titre", "Tapez un super titre pour votre annonce"))
            ->add('slug', TextType::class, $this->getConfiguration("Chaine URL", "Adresse web (automatique)",
                  ['required' => false]))
            ->add('introduction', TextType::class,
                   $this->getConfiguration("Introduction", "Donnez une description globale de l'annonce"))
            ->add('contenu', TextareaType::class, 
                   $this->getConfiguration("Description detaillée", "Tapez une description pour votre annonce !"))
           // ->add('brochure', FileType::class, [
           //     'label' => 'Files test',
           //     'mapped' => false,
           //     'required' => false
           // ])
           // ->add('imageFile', FileType::class, ['required' => false])
           ->add('coverImage',
                   UrlType::class, 
                   $this->getConfiguration("Url de l'image principale", "Donnez l'adresse d'une image qui donne vraiment envie"))
            ->add('typeBlog', EntityType::class, [
                'class' => TypeBlog::class,
                'choice_label' => 'name'
            ])
            ->add(
                'imageBlogs',
                CollectionType::class,
                [
                    'entry_type' => ImageBlogType::class,
                    'allow_add' => true,
                    'allow_delete' => true,
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Blog::class,
        ]);
    }
}

src/Controller/BlogController.php
<?php

namespace App\Controller;

use App\Entity\Blog;
use App\Entity\Search;
use App\Entity\Comment;
use App\Form\SearchType;
use App\Form\CommentType;
use App\Service\PaginationFront;
use App\Repository\BlogRepository;
use App\Repository\TypeBlogRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class BlogController extends AbstractController
{
    /**
     * @Route("/blog/{page<\d+>?1}", name="blog")
     */
    public function index(TypeBlogRepository $repo,BlogRepository $repos, $page, PaginationFront $pagination)
    {
        $typeBlog = $repo->findAll();
        $pagination->setEntityClass(Blog::class)
                   ->setPage($page);
        return $this->render('blog/index.html.twig', [
            'pagination' => $pagination,
            'types' => $typeBlog,
            'ads' => $repos->findLastAds(3)
        ]);
    }
    /**
     * Undocumented function
     *
     * @Route("/blog/search", name="blog_search")
     *
     * @param Request $request
     * @return Reponse
     */
    public function search(Request $request, BlogRepository $repo){
        $slug = $request->query->get('search');
        if($repo->findLikeSlug($slug) != null){
        return $this->redirectToROute('blog_show', [
            'slug' => $repo->findLikeSlug($slug)[0]->getSlug()
        ]);
        }else{
            return $this->render('blog/error404.html.twig');
        }
    }

    /**
     * Permet d'afficher une seule annonce
     * @Route("/blog/{slug}", name="blog_show")
     *@param Blog $blog
     * @return Response
     */
    public function show(Blog $blog, TypeBlogRepository $repo,BlogRepository $repos, Request $request, EntityManagerInterface $manager) {
        $typeBlog = $repo->findAll();
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);
        if($form->isSubmitted() && $form->isValid()){
            $comment->setBlog($blog);
            $manager->persist($comment);
            $manager->flush();
            $this->addFlash(
                'success',
                "Votre commentaire a éte bien pris compte");
        }
        return $this->render('blog/show.html.twig',
        [
        'ad' => $blog,
        'types' => $typeBlog,
        'ads' => $repos->findLastAds(3),
        'form' => $form->createView()
        ]
    );
    }
    
}

templates/blog/error404.html.twig
<!DOCTYPE html>
<html lang="fr">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>Dadch&amp;Co- 404</title>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,700" rel="stylesheet">

	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="/css/error/style.css" />

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->

</head>

<body>

	<div id="notfound">
		<div class="notfound">
			<div class="notfound-404">
				<h1>Oops!</h1>
				<h2>404 - The Page can't be found</h2>
			</div>
			<a href="{{ path('blog')}}">Go TO Blog page</a>
		</div>
	</div>

</body><!-- This templates was made by Colorlib (https://colorlib.com) -->

</html>

templates/blog/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces!{% endblock %}
 {% block description %}
        <meta name="description" content="Blog intéressant, Nos nouvelles, NOTRE ESPACE D'EXPRESSION">
        {% endblock %}
{% block body %}
<section class="full-height-baner h-70">
       <div class="empty-sp-lg-0 empty-sp-md-200 empty-sp-sm-200 empty-sp-xs-160"></div> 
        <div class="bg ready data-jarallax" data-jarallax="5" style="background-image:url(https://res.cloudinary.com/dadch-co-com/image/upload/v1589304222/dadch-co/blog/blog_paegry.jpg)"><div class="hold-layer-2"></div></div>
          <div class="main-baner vertical-align">
              <div class="container">
               <div class="row">
                  <div class="col-lg-12 col-md-12">
                    <div class="title-style-6 type-1">
                    <div class="empty-sp-sm-10 empty-sp-xs-10"></div>
                     <span class="border-cube"><span class="t-l"></span><span class="c-l"></span><span class="b-l"></span></span>
                     <span class="sub-caption-line lg"><span class="left"></span> <span>dadch&amp;co blog</span> <span class="right"></span></span>
                      <div class="empty-sp-sm-10 empty-sp-xs-10"></div>
                       <h1 class="caption-1 color-1">Nos nouvelles</h1>
                        <div class="empty-sp-sm-20 empty-sp-xs-10"></div>
                         <div class="simple-text size-2 color-1">
                             <p>NOTRE ESPACE D'EXPRESSION </p>
                         </div>
                         <div class="empty-sp-sm-10 empty-sp-xs-10"></div>
                     </div>  
                  </div>
               </div>  
              </div>
          </div>    
       <div class="empty-sp-lg-0 empty-sp-md-130 empty-sp-sm-200 empty-sp-xs-100"></div> 
     </section>
 <section class="section overflow-content page-style-2">
      <div class="empty-sp-md-200 empty-sp-sm-100 empty-sp-xs-100"></div>
	   <div class="container">
         <div class="title-style-1">
             <span class="sub-title-2">Blog intéressant</span>
         </div>
         <div class="empty-sp-md-70 empty-sp-sm-30 empty-sp-xs-30"></div>
	     <div class="row">
	         <div class="col-lg-8 col-md-12 col-xs-12">
                {% for ad in pagination.data %}
	            <div class="blog-post-item wow slideInLeft">
	                <div class="image hover-img">
	                   <div class="bg" style="background-image:url({{ad.coverImage}})"></div>
	                </div>
	                <div class="empty-sp-sm-25 empty-sp-xs-25"></div>
	                <div class="text">
                      <div class="post-time">
                        <span class="date-post">{{ad.createdAt|date("d/m/Y")}}</span>  
                        <a href="{{path('blog_show', {'slug': ad.slug})}}" class="date-post">{{ad.author.fullName}}</a>
                      </div>
                      <div class="empty-sp-sm-25 empty-sp-xs-25"></div>
	                    <a href="{{path('blog_show', {'slug': ad.slug})}}" class="title caption-3">{{ad.title}}</a>
                         <div class="empty-sp-sm-20 empty-sp-xs-20"></div>
	                      <div class="simple-text size-1 color-3">
	                          <p>{{ad.introduction}} </p>
	                      </div>
                          <div class="empty-sp-sm-25 empty-sp-xs-25"></div>
	                        <div class="tag-post-bar">
                              <div class="link fl">
	                            <a href="#">#expression ,</a>
	                            <a href="#">#inspiration ,</a>
	                            <a href="#">#travaille</a>
	                          </div>
	                          <div class="like fr">
                              {% if ad.comments | length > 0 %}
                                    {% include "partials/rating.html.twig" with {'rating': ad.avgRatings } %}
                                {% else %}    
                                    <small>Pas encore noté</small>
                                {% endif %}
	                              <a href="#" class="info-icon"><span>{{ad.avgRatings|number_format(1, ',', ' ')}}</span><i class="icon-heart-empty"></i></a>
	                              <a href="#" class="info-icon"><span>{{ad.comments|length}}</span><i class="icon-comment-empty"></i></a>
	                          </div>     
	                        </div>
	                </div>
	            </div>
	            
	            <div class="empty-sp-md-80 empty-sp-sm-40 empty-sp-xs-30"></div> 
                {% else %}
                 <h1>Aucun articles ajouter pour le moment !!!</h1>
                {% endfor %}
                <div class="empty-sp-md-80 empty-sp-sm-40 empty-sp-xs-30"></div>
                          
                {{pagination.display()}}
                           
                <div class="empty-sp-md-130 empty-sp-sm-100 empty-sp-xs-60"></div>                  
	                      
	         </div>
	         <div class="col-lg-4 col-md-12 col-xs-12">
	             <div class="blog-sidebar sidebar">
	                <form action="{{path('blog_search')}}" class="search-form wow slideInRight">
	                    <div class="input-group input-style-2">
                          <input type="text" class="form-control" name="search" placeholder="Rechercher un article..." required>
                          <span class="input-group-btn">
                            <button class="btn btn-secondary button-style-2" type="submit">rechercher</button>
                          </span>
                        </div>
	                </form>
	                <div class="empty-sp-md-60 empty-sp-sm-25 empty-sp-xs-30"></div>
	                <div class="sidebar-blog-item wow slideInRight">
	                   <h3 class="caption-3 title">categories d'article</h3>
                         <div class="empty-sp-md-30 empty-sp-sm-30 empty-sp-xs-20"></div>
	                     <ul class="category-list">
                            {% for type in types %}
	                         <li><a href="#">{{type.name}}<span>({{type.blog|length}})</span></a></li>
                            {% endfor %}
	                     </ul>
                    </div>
                    <div class="empty-sp-md-50 empty-sp-sm-20 empty-sp-xs-20"></div>
                    <div class="sidebar-blog-item wow slideInRight">
	                   <h3 class="caption-3 title">Derniers articles</h3>
                         <div class="empty-sp-md-30 empty-sp-sm-30 empty-sp-xs-20"></div>
                        {% for ad in ads %}
                           <div class="recent-post vertical-wrap">
                               <div class="image align-item hover-img">
                                   <a href="{{path('blog_show', {'slug': ad.annonce.slug})}}"><img src="{{ad.annonce.coverImage}}" alt="" class="resp-img"></a>
                               </div>
                               <div class="text align-item">
                                   <a href="{{path('blog_show', {'slug': ad.annonce.slug})}}" class="caption-4">{{ad.annonce.title}}</a>
                                 <div class="empty-sp-sm-25 empty-sp-xs-20"></div>
                                  <span class="date-post">{{ad.annonce.createdAt|date("d/m/Y")}}</span>
                               </div>
                           </div>
                           <div class="empty-sp-sm-30 empty-sp-xs-15"></div>
                        {% endfor %}
                    </div> 
                    
                    <div class="empty-sp-md-75 empty-sp-sm-80 empty-sp-xs-50"></div>
	             </div>
	         </div>
	     </div>
	   </div>
    </section>
{% endblock %}